# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrRBfB_5_UybKWkZMEAW63Vxjkyc_Map
"""

import pandas as pd
teachers=pd.DataFrame({
             'FISH' :[ 'Fozilov Nurbek ', 'Ergashev Shahboz','Hamidova Abdulaziz ',"Tojiboyev Laziz","Ergashev Faxriddin","Inomov N" ] ,
              "Tug'ilgan yili" :[    '2005',"2005","2005", "2004","2004","2005" ] ,
             "Yashash manzili" : [   "Farg'ona viloyati Farg'ona tumani","Andihon viloyati", "Farg'ona viloyati Toshloq tumani","Andijon viloyati Baliqchi tumani","Andihon viloyati","Andihon viloyati" ] ,
             "O'qish joyi" : [ 'TATUFF' ,'TATUFF','TATUFF','TATUFF','TATUFF','TATUFF'    ] ,
             "Yo'nalishi" : [   'raqamli iqtisodiyot' ,'raqamli iqtisodiyot','raqamli iqtisodiyot','raqamli iqtisodiyot','raqamli iqtisodiyot','raqamli iqtisodiyot'     ]



})
print(teachers)

teachers.to_excel("660-guruh teacher's.xlsx")